#!/bin/sh
scriptpath="$HOME/dotfiles/"

case $1 in
    pull)
        rsync -tarv --exclude={'slash', 'setup'} $scriptpath $HOME
    ;;
    rootpull)
        sudo rsync -tarv $scriptpath /root
    ;;
    push)
        find $scriptpath -mindepth 1 -type f -printf '%P\n' | grep -Evi '^.git|^slash|^setup' > /tmp/dotman
        rsync -tarv --files-from=/tmp/dotman $HOME $scriptpath
    ;;
    add)
        if [ -e "$2" ]
        then
            if [ -d "$2" ]
            then
                for line in "${@:2}"
                do
                    path=$scriptpath$(realpath --relative-to=$HOME $line)
                    if [ -n "$path" ] 
                        then
                            directory=$path
                            echo "Created directory $directory"
                            mkdir -p "$directory"
                        else
                            echo "Directory does not exist"
                    fi
                done
            else
                for line in "${@:2}"
                do
                    path=$scriptpath$(realpath --relative-to=$HOME $line)
                    if [ -n "$path" ] 
                        then
                            directory=$(echo $path | awk 'BEGIN{FS=OFS="/"} {$(NF)=""; print}')
                            echo "Created file $path"
                            mkdir -p "$directory" && touch "$file"
                        else
                            echo "File does not exist"
                    fi
                done
            fi
        else
            if [ -n "$2" ]
            then
                echo "File or directory does not exist"
            else
                echo "No file or directory specified"
            fi
        fi
    ;;
    rootpush)
        find $scriptpath -mindepth 1 -type f -printf '%P\n' | grep -Evi '^.git|^slash|^setup' > /tmp/dotman
        sudo rsync -tarv --files-from=/tmp/dotman /root $scriptpath
    ;; 
    slashpull)
        sudo rsync -tarv $scriptpath/slash $scriptpath /
    ;;
    slashpush)
        find $scriptpath/slash -mindepth 1 -type f -printf '%P\n' | grep -Evi '^.git|^slash|^setup' > /tmp/dotman
        sudo rsync -tarv --files-from=/tmp/dotman / $scriptpath/slash
    ;;
    *)
        echo 'Invalid argument'
    ;;
esac

# realpath $1
