#!/bin/sh
case $1 in
1)
	nitrogen --restore
	;;
2)
	nitrogen --set-zoom-fill "/home/rehpotsirhc/Nextcloud/Pictures/Anime/Christmas.jpg"
	;;
3)
	nitrogen --set-zoom-fill "/home/rehpotsirhc/Nextcloud/Pictures/Anime/Angel Beats.jpg"
	;;
4)
	nitrogen --set-zoom-fill "/home/rehpotsirhc/Nextcloud/Pictures/Anime/C3.jpg"
	;;
5)
	nitrogen --set-zoom-fill "/home/rehpotsirhc/Nextcloud/Pictures/Anime/Love of Ren'ai Koutei of LOVE!.jpg"
	;;
6)
	nitrogen --set-zoom-fill "/home/rehpotsirhc/Nextcloud/Pictures/Anime/Sora no Mukou de Sakimasu you ni.jpg"
	;;
7)
	nitrogen --set-zoom-fill "/home/rehpotsirhc/Nextcloud/Pictures/Anime/Majo Koi Nikki.jpg"
	;;
8)
	nitrogen --set-zoom-fill "/home/rehpotsirhc/Nextcloud/Pictures/Anime/Innocent Girl.jpg"
	;;
9)
	nitrogen --set-zoom-fill "/home/rehpotsirhc/Nextcloud/Pictures/Anime/Witch's Garden.jpg"
	;;
0)
	nitrogen --set-zoom-fill "/home/rehpotsirhc/Nextcloud/Pictures/Anime/Miniskirt Pirates.jpg"
	;;
*)
	echo "No valid arguments"
	;;
esac
